name: Automerge Branches

on: 
  push:
    branches:
      - automerge-testing
  workflow_dispatch: 

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the main repository
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          path: src 

      # Step 2: Checkout the secondary repository
      - name: Checkout zero-devops-utils repository
        uses: actions/checkout@v4
        with:
          repository: anunaidu/Copyright-checker
          path: cm-utils
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Read config.json for repositories and branches
      - name: Read config.json
        run: |
          config=$(cat config.json)
          echo "CONFIG=$config" >> $GITHUB_ENV

      # Step 4: Iterate over repositories and run the automerge script
      - name: Run Automerge for Multiple Repositories
        run: |
          repositories=$(echo "${CONFIG}" | jq -c '.repositories[]')
          for repo in $repositories; do
            REPO_NAME=$(echo "$repo" | jq -r '.name')
            SRC_BRANCH=$(echo "$repo" | jq -r '.source_branch')
            TARGET_BRANCH=$(echo "$repo" | jq -r '.target_branch')
            echo "Processing $REPO_NAME with source branch $SRC_BRANCH and target branch $TARGET_BRANCH..."

            # Set source and secondary repo URLs
            SRC_REPO_URL="https://github.com/anunaidu/$REPO_NAME.git"
            SECOND_REPO_URL="https://github.com/anunaidu/Copyright-checker.git"

            echo "Running Automerge Script for $SRC_BRANCH -> $TARGET_BRANCH...
            perl cm-utils/automerge/automerge-git-via-merge.pl \
              -r ${GITHUB_WORKSPACE}/src \
              -f "$SRC_BRANCH" \
              -t "$TARGET_BRANCH" \
              -s "$SRC_REPO_URL" \
              -b "$SECOND_REPO_URL" \
              -m "anu@gmail.com" -d -n"
          done
        env:
          CONFIG: ${{ env.CONFIG }}

      # Step 5: Clean up any temporary files or environment variables if needed
      - name: Cleanup
        run: |
          echo "Cleanup done!"
