name: Automerge Workflow

on:
  workflow_dispatch:
    inputs:
      srcBranch:
        description: 'Source branch to merge from'
        required: true
        type: string
      tgtBranch:
        description: 'Target branch to merge into'
        required: true
        type: string

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Check branch protection
        id: check_protection
        run: |
          protection_status=$(gh api repos/${{ github.repository }}/branches/${{ github.event.inputs.tgtBranch }}/protection --jq '.enabled')
          echo "protection_status=$protection_status" >> $GITHUB_ENV

      - name: Merge branches if not protected
        if: env.protection_status == 'false'
        run: |
          git checkout ${{ github.event.inputs.tgtBranch }}
          git merge ${{ github.event.inputs.srcBranch }}
          git push

      - name: Create PR if protected
        if: env.protection_status == 'true'
        run: |
          gh pr create --base ${{ github.event.inputs.tgtBranch }} --head ${{ github.event.inputs.srcBranch }} --title "Automerged PR from ${{ github.event.inputs.srcBranch }}" --body "Automerged PR"

      - name: Check for merge conflicts
        id: conflict_check
        run: |
          git checkout ${{ github.event.inputs.tgtBranch }}
          git merge ${{ github.event.inputs.srcBranch }} || echo "Conflict detected" > conflict.txt
          if [ -f conflict.txt ]; then
            echo "Merge conflicts detected. Sending email."
            # Configure your mail sending here
            mail mahi.naidu770@gmail.com
          fi

      - name: Send success email
        if: success()
        run: |
          echo "Workflow succeeded. Sending email."
          # Configure your mail sending here
           mail mahi.naidu770@gmail.com

      - name: Clean up
        run: |
          rm -f conflict.txt
