name: Automerge Branches

on:
  push:
    branches:
      - automerge-testing  # Trigger on pushes to this branch
  workflow_dispatch:
jobs:
  automerge:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3
        with:
          path: src
       

    
  

