name: Automerge Branches

on:
  push:
    branches:
      - automerge-testing  # Trigger on pushes to this branch
  workflow_dispatch:
jobs:
  automerge:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          path: src

      - name: List Repository Directory Contents
        run: |
          cd src  # Change to the checked-out repository directory
          echo "Current directory: $(pwd)"  # Print the current directory path
          ls -la  # List all files in the current directory

      - name: Checkout zero-devops-util repository
        uses: actions/checkout@v4
        with:
          repository: anunaidu/zero-devops-utils
          path: zero-devops-utils
          token: ${{ secrets.GITHUB_TOKEN }}
       

    
  

