name: Automerge Branches

on:
  workflow_dispatch:
    inputs:
      srcBranch:
        description: 'Source branch to merge from'
        required: true
        default: 'main'
      targetBranch:
        description: 'Target branch to merge into'
        required: true
        default: 'develop'
jobs:
  automerge:
    runs-on: ubuntu-latest

