name: Automerge via Webhook

on:
  repository_dispatch:
    types: [automerge-trigger]

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sample-repository
        uses: actions/checkout@v4
        with:
          path: src

      - name: Checkout automerge script repository
        uses: actions/checkout@v4
        with:
          repository: anunaidu/Copyright-checker
          path: cm-utils
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Source Repository URL
        run: |
          echo "SRC_REPO_URL=https://github.com/${{ github.event.client_payload.repo }}.git" >> $GITHUB_ENV

      - name: Run Automerge Script
        run: |
          for combination in "${{ toJson(github.event.client_payload.branch_combinations) }}"; do
            SRC_BRANCH=$(echo $combination | jq -r '.source_branch')
            TARGET_BRANCH=$(echo $combination | jq -r '.target_branch')
            MAILTO="anu@gmail.com" 
            DONT_RESOLVE="-d" 
            DONT_UPDATE="-n" 
            VERBOSE=""
            
            echo "Running Automerge Script for source branch: $SRC_BRANCH and target branch: $TARGET_BRANCH...

            perl cm-utils/automerge/automerge-git-via-merge.pl \
              -r ${GITHUB_WORKSPACE}/src \
              -f "$SRC_BRANCH" \
              -t "$TARGET_BRANCH" \
              -s "$SRC_REPO_URL" \
              -m "$MAILTO" ${DONT_RESOLVE} ${DONT_UPDATE} ${VERBOSE}"
          done
        env:
          SRC_REPO_URL: ${{ env.SRC_REPO_URL }}
