name: Automerge Branches

on:
  push:
    branches:
      - automerge-testing  # Trigger on pushes to this branch
  workflow_dispatch:  # Manual trigger

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the default repository (sample repository)
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          path: src  # Checkout directory is 'src'

      # Step 2: Checkout the zero-devops-utils repository
      - name: Checkout zero-devops-utils repository
        uses: actions/checkout@v4
        with:
          repository: anunaidu/Copyright-checker # Replace with your actual repository name
          path: cm-utils  # Checkout directory is 'cm-utils' where Perl script exists
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Show Git Remotes for src
        run: |
         cd src
         git remote -v
         
      # Step 3: Dynamically set repository URLs
      - name: Get Source Repository URL
        run: |
          SRC_REPO_URL="https://github.com/${GITHUB_REPOSITORY}.git"
          echo "Source repository URL: $SRC_REPO_URL"
          
      # Step 3: List the directory contents to verify checkouts
      - name: List Repository Directory Contents
        run: |
          echo "Listing contents of 'src' directory:"
          ls -la src
          echo "Listing contents of 'cm-utils' directory:"
          ls -la cm-utils
       

    
  

