# .github/workflows/automerge.yml in devops-utils
name: Automerge Branches

on:
  repository_dispatch:
    types: [automate_merge]

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout DevOps Utils Repo
        uses: actions/checkout@v4

      - name: Checkout Source Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.client_payload.source_repo }}
          path: source_repo
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Automerge Script
        run: |
          SRC_BRANCH="${{ github.event.client_payload.source_branch }}"
          TARGET_BRANCH="${{ github.event.client_payload.target_branch }}"
          VERBOSE="${{ github.event.client_payload.verbose }}"

          echo "Merging $SRC_BRANCH into $TARGET_BRANCH..."

          # Call your Perl script here
          "perl ./source_repo/path/to/your-script.pl \
            -s "$SRC_BRANCH" \
            -t "$TARGET_BRANCH" \
            -v "$VERBOSE" # Pass any other arguments as needed"
