name: Trigger Automerge

on:
  push: # This listens for push events, you can change it to whatever event you prefer

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Automerge
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{
              "event_type": "automate_merge",
              "client_payload": {
                "source_repo": "anunaidu/test1",  # Full repository name
                "source_branch": "rel1",            # The branch to merge from
                "target_branch": "dev",              # The branch to merge into
                "verbose": "false"                   # Optional verbose flag
              }
            }' \
            https://api.github.com/repos/anunaidu/sample-repository/dispatches

