name: Trigger Automerge

on:
  repository_dispatch:
    types: [automate_merge]

jobs:
  trigger:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      workflows: write

    steps:
      - name: Trigger Automerge
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{
              "event_type": "automate_merge",
              "client_payload": {
                "source_repo": "anunaidu/zero-devops-utils",
                "source_branch": "test1",
                "target_branch": "main",
                "verbose": "false"
              }
            }' \
            https://api.github.com/repos/anunaidu/sample-repository/dispatches



