# .github/workflows/trigger-automerge.yml in devops-utils
name: Trigger Automerge

on:
  push: # This listens for push events, you can change it to whatever event you prefer

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Automerge
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{
              "event_type": "automate_merge",
              "client_payload": {
                "source_repo": "zero-devops-utils",  # Replace with the actual repository name
                "source_branch": "test1",  # The branch to merge from
                "target_branch": "main",    # The branch to merge into
                "verbose": "false"         # Optional verbose flag
              }
            }' \
            https://api.github.com/repos/anunaidu/sample-repository/dispatches
